# This is a basic workflow to help you get started with Actions

name: Tests

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
   test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'

      - name: Run tests
        run: mvn test
